import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { createServiceClient } from '@/lib/supabase/server'
import { deductCreditsForAction, refundCreditsForAction } from '@/lib/credits/deduct'
import { uploadAvatarToStorage } from '@/lib/avatars/storage'
import { LEGO_TRANSFORM_PROMPT } from '@/lib/avatars/config'
import { createGeminiClient, GEMINI_CONFIG } from '@/lib/gemini/client'
import sharp from 'sharp'

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient()
    const serviceClient = createServiceClient()

    const { data: { user }, error: authError } = await supabase.auth.getUser()
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const formData = await request.formData()
    const imageFile = formData.get('image') as File
    const projectId = formData.get('projectId') as string

    if (!imageFile || !projectId) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      )
    }

    const validTypes = ['image/jpeg', 'image/png', 'image/webp']
    if (!validTypes.includes(imageFile.type)) {
      return NextResponse.json(
        { error: 'Invalid file type. Please upload JPEG, PNG, or WebP' },
        { status: 400 }
      )
    }

    const maxSize = 2 * 1024 * 1024
    if (imageFile.size > maxSize) {
      return NextResponse.json(
        { error: 'File too large. Maximum size is 2MB' },
        { status: 400 }
      )
    }

    const deductResult = await deductCreditsForAction({
      userId: user.id,
      actionType: 'avatar_generation',
      description: `LEGO avatar transformation for project ${projectId}`,
      supabase: serviceClient,
    })

    if (!deductResult.success) {
      return NextResponse.json(
        {
          error: 'insufficient_credits',
          message: 'Not enough credits for avatar generation. 15 credits required.',
          balance: deductResult.balance,
        },
        { status: 200 }
      )
    }

    let transformedImageBuffer: Buffer
    
    try {
      const imageBuffer = Buffer.from(await imageFile.arrayBuffer())
      const base64Image = imageBuffer.toString('base64')

      const gemini = createGeminiClient()
      
      // Use the same image as both project image and reference for identity preservation
      const contents = [
        { text: LEGO_TRANSFORM_PROMPT },
        {
          inlineData: {
            mimeType: imageFile.type,
            data: base64Image
          }
        },
        {
          inlineData: {
            mimeType: imageFile.type,
            data: base64Image
          }
        },
        {
          text: "\n\nIMPORTANT: Use the second image as a reference to maintain the person's identity and facial features. Create a LEGO minifigure that resembles the person in the reference image while applying the LEGO style transformation to the first image."
        }
      ]

      let response
      try {
        response = await gemini.models.generateContent({
          model: GEMINI_CONFIG.model,
          contents: contents,
          config: {
            responseModalities: GEMINI_CONFIG.responseModalities,
            imageConfig: GEMINI_CONFIG.imageConfig,
          },
        })
      } catch (geminiError: any) {
        console.error('Gemini API error (first attempt):', geminiError)
        
        await new Promise(resolve => setTimeout(resolve, 2000))
        
        response = await gemini.models.generateContent({
          model: GEMINI_CONFIG.model,
          contents: contents,
          config: {
            responseModalities: GEMINI_CONFIG.responseModalities,
            imageConfig: GEMINI_CONFIG.imageConfig,
          },
        })
      }

      if (!response?.candidates?.[0]?.content?.parts) {
        throw new Error('No response received from Gemini')
      }

      // Extract the generated image from the response
      let generatedBuffer: Buffer | undefined = undefined
      
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData?.data) {
          const imageData = part.inlineData.data
          generatedBuffer = Buffer.from(imageData, 'base64')
          break
        } else if (part.text) {
          console.log('Gemini response text:', part.text)
        }
      }
      
      if (!generatedBuffer) {
        throw new Error('No image generated by Gemini')
      }
      
      // Light compression to ensure file stays within size limits
      const compressedBuffer = await sharp(generatedBuffer)
        .png({
          quality: 70, // Lower quality for smaller file size
          compressionLevel: 9
        })
        .toBuffer()
      
      transformedImageBuffer = compressedBuffer
    } catch (error: any) {
      console.error('Failed to transform image:', error)
      
      await refundCreditsForAction({
        userId: user.id,
        actionType: 'avatar_generation',
        supabase: serviceClient,
      })

      return NextResponse.json(
        {
          error: 'transformation_failed',
          message: 'Failed to transform image. Your credits have been refunded.',
        },
        { status: 200 }
      )
    }

    let publicUrl: string
    try {
      publicUrl = await uploadAvatarToStorage({
        file: transformedImageBuffer,
        mimeType: 'image/png',
        userId: user.id,
        bucket: 'project-avatars',
        entityId: projectId,
      })
    } catch (error: any) {
      console.error('Failed to upload transformed image:', error)
      
      await refundCreditsForAction({
        userId: user.id,
        actionType: 'avatar_generation',
        supabase: serviceClient,
      })

      return NextResponse.json(
        {
          error: 'upload_failed',
          message: 'Failed to upload transformed image. Your credits have been refunded.',
        },
        { status: 200 }
      )
    }

    const { error: updateError } = await serviceClient
      .from('projects')
      .update({ project_avatar_url: publicUrl })
      .eq('id', projectId)
      .eq('user_id', user.id)

    if (updateError) {
      console.error('Failed to update project avatar URL:', updateError)
      return NextResponse.json(
        { error: 'Failed to update project' },
        { status: 500 }
      )
    }

    return NextResponse.json({
      success: true,
      avatarUrl: publicUrl,
    })
  } catch (error: any) {
    console.error('Unexpected error in avatar transform:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}
