// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MilestoneCreate
 */
export type MilestoneCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Target Date
     */
    target_date?: string | null;
    /**
     * Is Completed
     */
    is_completed?: boolean;
    /**
     * Project Id
     */
    project_id: string;
};

/**
 * MilestoneResponse
 */
export type MilestoneResponse = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Target Date
     */
    target_date?: string | null;
    /**
     * Is Completed
     */
    is_completed?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * ProjectCreate
 */
export type ProjectCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Deadline
     */
    deadline?: string | null;
    /**
     * Priority
     */
    priority?: string | null;
    /**
     * Knows Steps
     */
    knows_steps?: boolean | null;
    /**
     * Status
     */
    status?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
};

/**
 * ProjectResponse
 */
export type ProjectResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Deadline
     */
    deadline?: string | null;
    /**
     * Priority
     */
    priority?: string | null;
    /**
     * Knows Steps
     */
    knows_steps?: boolean | null;
    /**
     * Status
     */
    status?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * ProjectUpdate
 */
export type ProjectUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Deadline
     */
    deadline?: string | null;
    /**
     * Priority
     */
    priority?: string | null;
    /**
     * Knows Steps
     */
    knows_steps?: boolean | null;
    /**
     * Status
     */
    status?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * SessionCreate
 */
export type SessionCreate = {
    /**
     * Project Id
     */
    project_id?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * SessionResponse
 */
export type SessionResponse = {
    /**
     * Project Id
     */
    project_id?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Start Time
     */
    start_time: string;
    /**
     * End Time
     */
    end_time?: string | null;
    /**
     * Duration Minutes
     */
    duration_minutes?: number | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * SessionTaskResponse
 */
export type SessionTaskResponse = {
    /**
     * Task Id
     */
    task_id: string;
    /**
     * Time Spent Minutes
     */
    time_spent_minutes?: number;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * TaskCreate
 */
export type TaskCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Priority
     */
    priority?: string;
    /**
     * Status
     */
    status?: string;
    /**
     * Estimated Minutes
     */
    estimated_minutes?: number | null;
    /**
     * Actual Minutes
     */
    actual_minutes?: number;
    /**
     * Due Date
     */
    due_date?: string | null;
    /**
     * Project Id
     */
    project_id: string;
};

/**
 * TaskResponse
 */
export type TaskResponse = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Priority
     */
    priority?: string;
    /**
     * Status
     */
    status?: string;
    /**
     * Estimated Minutes
     */
    estimated_minutes?: number | null;
    /**
     * Actual Minutes
     */
    actual_minutes?: number;
    /**
     * Due Date
     */
    due_date?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Email
     */
    email: string;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type RegisterUserUsersRegisterPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/register';
};

export type RegisterUserUsersRegisterPostResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type RegisterUserUsersRegisterPostResponse = RegisterUserUsersRegisterPostResponses[keyof RegisterUserUsersRegisterPostResponses];

export type GetCurrentUserProfileUsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetCurrentUserProfileUsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetCurrentUserProfileUsersMeGetResponse = GetCurrentUserProfileUsersMeGetResponses[keyof GetCurrentUserProfileUsersMeGetResponses];

export type ListProjectsProjectsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Active Only
         */
        active_only?: boolean;
    };
    url: '/projects';
};

export type ListProjectsProjectsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListProjectsProjectsGetError = ListProjectsProjectsGetErrors[keyof ListProjectsProjectsGetErrors];

export type ListProjectsProjectsGetResponses = {
    /**
     * Response List Projects Projects Get
     *
     * Successful Response
     */
    200: Array<ProjectResponse>;
};

export type ListProjectsProjectsGetResponse = ListProjectsProjectsGetResponses[keyof ListProjectsProjectsGetResponses];

export type CreateProjectProjectsPostData = {
    body: ProjectCreate;
    path?: never;
    query?: never;
    url: '/projects';
};

export type CreateProjectProjectsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectProjectsPostError = CreateProjectProjectsPostErrors[keyof CreateProjectProjectsPostErrors];

export type CreateProjectProjectsPostResponses = {
    /**
     * Successful Response
     */
    201: ProjectResponse;
};

export type CreateProjectProjectsPostResponse = CreateProjectProjectsPostResponses[keyof CreateProjectProjectsPostResponses];

export type DeleteProjectProjectsProjectIdDeleteData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/projects/{project_id}';
};

export type DeleteProjectProjectsProjectIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProjectProjectsProjectIdDeleteError = DeleteProjectProjectsProjectIdDeleteErrors[keyof DeleteProjectProjectsProjectIdDeleteErrors];

export type DeleteProjectProjectsProjectIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteProjectProjectsProjectIdDeleteResponse = DeleteProjectProjectsProjectIdDeleteResponses[keyof DeleteProjectProjectsProjectIdDeleteResponses];

export type GetProjectProjectsProjectIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/projects/{project_id}';
};

export type GetProjectProjectsProjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectProjectsProjectIdGetError = GetProjectProjectsProjectIdGetErrors[keyof GetProjectProjectsProjectIdGetErrors];

export type GetProjectProjectsProjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponse;
};

export type GetProjectProjectsProjectIdGetResponse = GetProjectProjectsProjectIdGetResponses[keyof GetProjectProjectsProjectIdGetResponses];

export type UpdateProjectProjectsProjectIdPatchData = {
    body: ProjectUpdate;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/projects/{project_id}';
};

export type UpdateProjectProjectsProjectIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProjectProjectsProjectIdPatchError = UpdateProjectProjectsProjectIdPatchErrors[keyof UpdateProjectProjectsProjectIdPatchErrors];

export type UpdateProjectProjectsProjectIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponse;
};

export type UpdateProjectProjectsProjectIdPatchResponse = UpdateProjectProjectsProjectIdPatchResponses[keyof UpdateProjectProjectsProjectIdPatchResponses];

export type ListProjectMilestonesProjectsProjectIdMilestonesGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/projects/{project_id}/milestones';
};

export type ListProjectMilestonesProjectsProjectIdMilestonesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListProjectMilestonesProjectsProjectIdMilestonesGetError = ListProjectMilestonesProjectsProjectIdMilestonesGetErrors[keyof ListProjectMilestonesProjectsProjectIdMilestonesGetErrors];

export type ListProjectMilestonesProjectsProjectIdMilestonesGetResponses = {
    /**
     * Response List Project Milestones Projects  Project Id  Milestones Get
     *
     * Successful Response
     */
    200: Array<MilestoneResponse>;
};

export type ListProjectMilestonesProjectsProjectIdMilestonesGetResponse = ListProjectMilestonesProjectsProjectIdMilestonesGetResponses[keyof ListProjectMilestonesProjectsProjectIdMilestonesGetResponses];

export type CreateMilestoneProjectsProjectIdMilestonesPostData = {
    body: MilestoneCreate;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/projects/{project_id}/milestones';
};

export type CreateMilestoneProjectsProjectIdMilestonesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMilestoneProjectsProjectIdMilestonesPostError = CreateMilestoneProjectsProjectIdMilestonesPostErrors[keyof CreateMilestoneProjectsProjectIdMilestonesPostErrors];

export type CreateMilestoneProjectsProjectIdMilestonesPostResponses = {
    /**
     * Successful Response
     */
    201: MilestoneResponse;
};

export type CreateMilestoneProjectsProjectIdMilestonesPostResponse = CreateMilestoneProjectsProjectIdMilestonesPostResponses[keyof CreateMilestoneProjectsProjectIdMilestonesPostResponses];

export type ListMilestoneTasksMilestonesMilestoneIdTasksGetData = {
    body?: never;
    path: {
        /**
         * Milestone Id
         */
        milestone_id: string;
    };
    query?: never;
    url: '/milestones/{milestone_id}/tasks';
};

export type ListMilestoneTasksMilestonesMilestoneIdTasksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMilestoneTasksMilestonesMilestoneIdTasksGetError = ListMilestoneTasksMilestonesMilestoneIdTasksGetErrors[keyof ListMilestoneTasksMilestonesMilestoneIdTasksGetErrors];

export type ListMilestoneTasksMilestonesMilestoneIdTasksGetResponses = {
    /**
     * Response List Milestone Tasks Milestones  Milestone Id  Tasks Get
     *
     * Successful Response
     */
    200: Array<TaskResponse>;
};

export type ListMilestoneTasksMilestonesMilestoneIdTasksGetResponse = ListMilestoneTasksMilestonesMilestoneIdTasksGetResponses[keyof ListMilestoneTasksMilestonesMilestoneIdTasksGetResponses];

export type CreateTaskMilestonesMilestoneIdTasksPostData = {
    body: TaskCreate;
    path: {
        /**
         * Milestone Id
         */
        milestone_id: string;
    };
    query?: never;
    url: '/milestones/{milestone_id}/tasks';
};

export type CreateTaskMilestonesMilestoneIdTasksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskMilestonesMilestoneIdTasksPostError = CreateTaskMilestonesMilestoneIdTasksPostErrors[keyof CreateTaskMilestonesMilestoneIdTasksPostErrors];

export type CreateTaskMilestonesMilestoneIdTasksPostResponses = {
    /**
     * Successful Response
     */
    201: TaskResponse;
};

export type CreateTaskMilestonesMilestoneIdTasksPostResponse = CreateTaskMilestonesMilestoneIdTasksPostResponses[keyof CreateTaskMilestonesMilestoneIdTasksPostResponses];

export type CompleteTaskTasksTaskIdCompletePatchData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/tasks/{task_id}/complete';
};

export type CompleteTaskTasksTaskIdCompletePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompleteTaskTasksTaskIdCompletePatchError = CompleteTaskTasksTaskIdCompletePatchErrors[keyof CompleteTaskTasksTaskIdCompletePatchErrors];

export type CompleteTaskTasksTaskIdCompletePatchResponses = {
    /**
     * Successful Response
     */
    200: TaskResponse;
};

export type CompleteTaskTasksTaskIdCompletePatchResponse = CompleteTaskTasksTaskIdCompletePatchResponses[keyof CompleteTaskTasksTaskIdCompletePatchResponses];

export type SkipTaskTasksTaskIdSkipPatchData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/tasks/{task_id}/skip';
};

export type SkipTaskTasksTaskIdSkipPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SkipTaskTasksTaskIdSkipPatchError = SkipTaskTasksTaskIdSkipPatchErrors[keyof SkipTaskTasksTaskIdSkipPatchErrors];

export type SkipTaskTasksTaskIdSkipPatchResponses = {
    /**
     * Successful Response
     */
    200: TaskResponse;
};

export type SkipTaskTasksTaskIdSkipPatchResponse = SkipTaskTasksTaskIdSkipPatchResponses[keyof SkipTaskTasksTaskIdSkipPatchResponses];

export type CreateSessionSessionsPostData = {
    body: SessionCreate;
    path?: never;
    query?: never;
    url: '/sessions';
};

export type CreateSessionSessionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSessionSessionsPostError = CreateSessionSessionsPostErrors[keyof CreateSessionSessionsPostErrors];

export type CreateSessionSessionsPostResponses = {
    /**
     * Successful Response
     */
    201: SessionResponse;
};

export type CreateSessionSessionsPostResponse = CreateSessionSessionsPostResponses[keyof CreateSessionSessionsPostResponses];

export type GetSessionTasksSessionsSessionIdTasksGetData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/sessions/{session_id}/tasks';
};

export type GetSessionTasksSessionsSessionIdTasksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSessionTasksSessionsSessionIdTasksGetError = GetSessionTasksSessionsSessionIdTasksGetErrors[keyof GetSessionTasksSessionsSessionIdTasksGetErrors];

export type GetSessionTasksSessionsSessionIdTasksGetResponses = {
    /**
     * Response Get Session Tasks Sessions  Session Id  Tasks Get
     *
     * Successful Response
     */
    200: Array<SessionTaskResponse>;
};

export type GetSessionTasksSessionsSessionIdTasksGetResponse = GetSessionTasksSessionsSessionIdTasksGetResponses[keyof GetSessionTasksSessionsSessionIdTasksGetResponses];

export type EndSessionSessionsSessionIdEndPostData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/sessions/{session_id}/end';
};

export type EndSessionSessionsSessionIdEndPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EndSessionSessionsSessionIdEndPostError = EndSessionSessionsSessionIdEndPostErrors[keyof EndSessionSessionsSessionIdEndPostErrors];

export type EndSessionSessionsSessionIdEndPostResponses = {
    /**
     * Successful Response
     */
    200: SessionResponse;
};

export type EndSessionSessionsSessionIdEndPostResponse = EndSessionSessionsSessionIdEndPostResponses[keyof EndSessionSessionsSessionIdEndPostResponses];

export type DebugJwtDebugJwtPostData = {
    /**
     * Request
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/debug/jwt';
};

export type DebugJwtDebugJwtPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DebugJwtDebugJwtPostError = DebugJwtDebugJwtPostErrors[keyof DebugJwtDebugJwtPostErrors];

export type DebugJwtDebugJwtPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
